cp ./libchromatix_mt9e013_preview.so ./out/ -r
cp ./libmmcamera_imx091.so ./out/ -r
cp ./libchromatix_imx135_video_hdr.so ./out/ -r
cp ./libchromatix_imx135_zsl.so ./out/ -r
cp ./libchromatix_s5k3l1yx_hfr_60fps.so ./out/ -r
cp ./libchromatix_imx132_video_hd.so ./out/ -r
cp ./libchromatix_ov5648_video_hd.so ./out/ -r
cp ./libchromatix_imx091_preview.so ./out/ -r
cp ./libchromatix_imx135_default_video.so ./out/ -r
cp ./libchromatix_ov9726_default_video.so ./out/ -r
cp ./libchromatix_s5k4e1_preview.so ./out/ -r
cp ./libchromatix_s5k3l1yx_preview.so ./out/ -r
cp ./libchromatix_ov9726_preview.so ./out/ -r
cp ./libchromatix_s5k3l1yx_default_video.so ./out/ -r
cp ./libchromatix_ov2720_zsl.so ./out/ -r
cp ./libchromatix_imx074_video_hd.so ./out/ -r
cp ./libchromatix_imx135_video_hd.so ./out/ -r
cp ./libmmcamera_image_stab.so ./out/ -r
cp ./libchromatix_s5k3l1yx_zsl.so ./out/ -r
cp ./libCameraEffect.so ./out/ -r
cp ./libchromatix_imx132_default_video.so ./out/ -r
cp ./libchromatix_mt9e013_default_video.so ./out/ -r
cp ./libchromatix_imx132_zsl.so ./out/ -r
cp ./libchromatix_ov8825_default_video.so ./out/ -r
cp ./libchromatix_imx074_zsl.so ./out/ -r
cp ./libchromatix_ov8825_preview.so ./out/ -r
cp ./libchromatix_s5k3l1yx_hfr_90fps.so ./out/ -r
cp ./libchromatix_ov5647_default_video.so ./out/ -r
cp ./libchromatix_s5k3l1yx_hfr_120fps.so ./out/ -r
cp ./libchromatix_s5k3l1yx_video_hd.so ./out/ -r
cp ./libchromatix_imx091_default_video.so ./out/ -r
cp ./libchromatix_ov2720_preview.so ./out/ -r
cp ./libchromatix_ov5648_zsl.so ./out/ -r
cp ./libchromatix_mt9e013_video_hfr.so ./out/ -r
cp ./libchromatix_imx091_zsl.so ./out/ -r
cp ./libchromatix_imx074_default_video.so ./out/ -r
cp ./libchromatix_ov2720_default_video.so ./out/ -r
cp ./liboemcamera.so ./out/ -r
cp ./libchromatix_imx135_preview.so ./out/ -r
cp ./libchromatix_ov5648_preview.so ./out/ -r
cp ./libchromatix_imx132_preview.so ./out/ -r
cp ./libchromatix_ov5647_preview.so ./out/ -r
cp ./libchromatix_imx074_preview.so ./out/ -r
cp ./libchromatix_imx091_video_hd.so ./out/ -r
cp ./libchromatix_ov5648_default_video.so ./out/ -r
cp ./libchromatix_s5k4e1_default_video.so ./out/ -r
cp ./libchromatix_ov2720_hfr.so ./out/ -r
